default:
  debug: true
  digest: false
  compress: false
development:
  debug: true
production:
  debug: false
  digest: true
  compress: true
  asset_host: "http://goboundless.github.com/spar"
  deploy_strategy: local
  deploy_path: '../spar-pages-compiled'

